### ISSUE TITLE
Look into release-it for npm releases

### ISSUE THREAD

**Issue by amyrlam** [hashicorp/flight#115]
https://github.com/release-it/release-it

@MelSumner uses it here https://github.com/ember-a11y/ember-a11y-refocus/blob/master/RELEASE.md

**Comment by MelSumner** [comment]
@Dhaulagiri @didoo I think we should integrate this into the Ember addon. It takes care of some of the otherwise manual (and therefore subject to potential error) stuff out of the way.

**Comment by didoo** [comment]
@MelSumner yes, I was looking into Lerna as possible solution to release multiple packages at the same time. I'll add `release-it` to the list of things to look into with @amyrlam in the context of the "release" step of the Node script.

**Comment by amyrlam** [comment]
synced with didoo. i am going to give release-it a spin now, and cristiano will check out lerna

**Comment by amyrlam** [comment]
It seems safe to close this as took a different approach in https://github.com/hashicorp/flight/pull/225. Let's have Melanie, Cristiano, or Brian do the next npm release to test our process.

BTW if I'm incorrectly closing, feel free to reopen the issue!
