### ISSUE TITLE
Marketing: `learn` with icons that are < 16, how to address

### ISSUE THREAD

**Issue by amyrlam** [hashicorp/flight#137]
Brayden will send Amy some stuff, maybe this week, perhaps even in Figma / screenshot as not in the code yet (will come in the code, when they use the api to actually show progress). Relates to: https://github.com/hashicorp/flight/issues/124

Get Hector / team and Brayden discussing when have a shareable example

**Comment by amyrlam** [comment]
@dizzyup @didoo wanted to get the conversation started with @braydenlove (designer) and @kendallstrautman (engineer) from marketing / HashiCorp learn page.

Brayden shared https://www.figma.com/file/UmFXOU5iPm7ioRqyd8j48k/Learn-Design-Spec-2.0?node-id=920%3A60164 which shows some of the smaller icons like the "in progress hover". Wondering how to move forward with these designs given that stylistically they are looking for < 16, if I'm summarizing the issue correctly.

It's not in the UI yet but coming soon. 

This all kinda relates to the convo on https://github.com/hashicorp/flight/pull/119.

**Comment by braydenlove** [comment]
Happy to fill in any gaps or answer any ?s you might have.

**Comment by amyrlam** [comment]
hector is chatting with brayden and cris, may be a one-off

**Comment by amyrlam** [comment]
This can also kinda be folded into https://github.com/hashicorp/design-systems-team/pull/30, depending on how we want to "track" this kind of external stuff cc @didoo

**Comment by braydenlove** [comment]
Chatted with Hector and figured that some of our specific use cases will be one-off. We will be using flight as a base but need to pivot based on very particular sizing constraints.

**Comment by amyrlam** [comment]
synced with @braydenlove, who spoke with @dizzyup
- for icons < 16, use 16
- for icons > 24, use 24
- can have one-off solutions if needed, didn't seem like an issue for brayden and cris's project

it seems like this can be closed and maybe will be fleshed out in the design docs as needed down the road. if i'm wrong please feel free to reopen the issue!
