### ISSUE TITLE
Verify svgo working as expected

### ISSUE THREAD

**Issue by amyrlam** [hashicorp/flight#144]
> @johncowen hey, feel free to chime in whenever i would say!

👍 

> icons should not be scaled in new code. but... (1) there may be exceptions in new code. (2) that may not be possible / feasible in all legacy code.
> 
> we've run into situations already where the icon is in line with typography that's 20px high in boundary-ui, or a smaller icon like 11px is being used in learn. so... looking for us to flesh out the guidelines as we're trying to build adoption of the package

aaahhh right gotcha, thanks for the info. In that case my first thought here would be maybe 'should'?

> ..., consumers **should not** stretch

Something like that ^ maybe is more or less what we are saying here? Dunno up to you folks.

> there are 2 packages: https://www.npmjs.com/package/@hashicorp/ember-flight-icons and https://www.npmjs.com/package/@hashicorp/flight-icons. i think you may be able to use flight-icons with the css approach in consul, but i haven't dug into it yet, we could pair next week if you want? (i'll be out fri & tue, extending the long weekend)

Yeah for sure, it's super good for us at the moment 👍 

I had to double look here as I thought I'd misunderstood which README this was for, we are talking about the README for the icons only package here right? Maybe I've misunderstood that this is meant for the all the ember stuff on top also, sorry if so!

> i thought the icons were svgo'd, can you be more specific about what are you seeing? i can file that as a separate bug ticket if can get more detail! also, feel free to file atomic issues on flight at will, helps for tracking

Oh weird, maybe I'm doing something wrong 👀 , will take a look first to check. The thing I noticed was, as Consul inlines the SVGs into CSS using a script, whilst it does this it doesn't actually inline the SVG onto a single line, so when I ran the script on these icons the output was all broken:

```css
background-image: url('stuff:<svg><g></g></svg>')
/*vs*/
background-image: url('stuff:<svg>
  <g>
  </g>
</svg>')
```

My first thought was "oh I need to run svgo on the icons", when I did that it removed all the whitespace from the svg and the CSS output script then worked like:

```css
background-image: url('stuff:<svg><g></g></svg>')
```

I think I remember that you can pass different config to svgo or something, maybe its that, I was just using `svgo -i ./folder`.

_Originally posted by @johncowen in https://github.com/hashicorp/flight/issues/119#issuecomment-911427964_

**Comment by Dhaulagiri** [comment]
We can confirm the correct behavior when we re-write the export. It is very possible this isn't actually working right now.

**Comment by didoo** [comment]
@amyrlam @Dhaulagiri yes, this will be tackled anyway in the Node version of the export script

**Comment by Dhaulagiri** [comment]
Closed by https://github.com/hashicorp/flight/pull/196
