### ISSUE TITLE
Implement header redesign

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/flight#165]
<img width="1085" alt="Screen Shot 2021-09-08 at 19 58 28" src="https://user-images.githubusercontent.com/1672302/132604919-c08747d3-d998-4853-b544-03362f328de6.png">

**Comment by heatherlarsen** [comment]
Design iteration based on feedback:
<img width="1446" alt="header-desktop" src="https://user-images.githubusercontent.com/8553306/133310361-a0d3ab3b-b343-4c6b-9bb1-a4bf15a7b286.png">
