### ISSUE TITLE
Implement icon card redesign

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/flight#166]
<img width="189" alt="Screen Shot 2021-09-08 at 19 58 52" src="https://user-images.githubusercontent.com/1672302/132604956-ac6826b4-1380-46db-a48b-7d95a30787f9.png">

Note: clipboard icon and functionality should be considered a separate piece of work

**Comment by heatherlarsen** [comment]
Including states:
<img width="188" alt="icon-card-example" src="https://user-images.githubusercontent.com/8553306/133309966-29aa4763-7b43-4042-a139-9e34e73bc8dd.png">

There are some accessibility concerns/considerations we need to make in regards to the copy icon only being displayed on hover, which will need further discussion with @MelSumner and @dizzyup.
