### ISSUE TITLE
Implement new hero section redesign

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/flight#167]
<img width="1021" alt="Screen Shot 2021-09-08 at 19 59 43" src="https://user-images.githubusercontent.com/1672302/132605022-0fba5cc5-9ded-4c05-a0e4-d905573b7dc3.png">

**Comment by heatherlarsen** [comment]
Design iteration to align to microsite & update Design icon
<img width="1016" alt="hero" src="https://user-images.githubusercontent.com/8553306/133278520-2e043f1a-6df2-461b-aa48-0c91cdb8b7a9.png">
