### ISSUE TITLE
Implement search box redesign

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/flight#168]
<img width="853" alt="Screen Shot 2021-09-08 at 20 00 31" src="https://user-images.githubusercontent.com/1672302/132605085-4f8c6bf3-83ff-4ea5-909e-664d8f0aaa9a.png">

**Comment by heatherlarsen** [comment]
Design iteration based on feedback:
<img width="863" alt="form-input-example" src="https://user-images.githubusercontent.com/8553306/133277905-a0932044-6923-41a2-865c-2f38b768f457.png">
