### ISSUE TITLE
Implement new icon size toggle functionality

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/flight#169]
<img width="1025" alt="Screen Shot 2021-09-08 at 20 01 17" src="https://user-images.githubusercontent.com/1672302/132605155-b540b7b3-a083-4e3f-8e92-69b5a3e16061.png">

Provided this design is reasonably straightforward to implement, toggling the button should switch between rendering 16px and 24px icons.

**Comment by MelSumner** [comment]
Resolved with #182  and #199
