### ISSUE TITLE
Test ember-flight-icons in cloud-ui / Make passing in icon color easier

### ISSUE THREAD

**Issue by amyrlam** [hashicorp/flight#17]
Circle back with @venusang re: https://github.com/hashicorp/cloud-ui/pull/1217 / https://hashicorp.slack.com/archives/CPB8GS9QT/p1627069656308600.

Milestone-wise, kind of a part of Implementation and Migration? 

Extracted from https://github.com/hashicorp/flight/issues/8#issuecomment-885931022 as separate task.

**Comment by MelSumner** [comment]
@amyrlam I documented some of the known things here: https://github.com/hashicorp/flight/issues/54

**Comment by amyrlam** [comment]
i'm stumped what i'm doing wrong in cloud-ui. just threw something on venus's calendar to see if she's free monday to pair. was easy as pie in https://github.com/hashicorp/design-system-playground/pull/3

**Comment by amyrlam** [comment]
^^ sorted

- [ ] get the PR ready, then ask for a vercel link
- [ ] from @Dhaulagiri: had talked to matthew, get a ticket on their backlog to see who will implement

**Comment by amyrlam** [comment]
the color aspect is most definitely DONE!

brian and amy went to tce guild meeting. moving the "get them to implement" phase to https://github.com/hashicorp/design-systems-team/pull/30 since these tickets have all been a bit murky
