### ISSUE TITLE
Move Design Contributing to Design Docs

### ISSUE THREAD

**Issue by heatherlarsen** [hashicorp/flight#175]
Still catching up, looks like this was all brought in as part of https://github.com/hashicorp/flight/pull/157/files except for this section "How to contribute a new icon in Figma (HashiCorp staff only)" do you still want to merge that part in? @heatherlarsen @MelSumner

_Originally posted by @amyrlam in https://github.com/hashicorp/flight/pull/147#discussion_r704821123_

Need to move Design Contribution details in the README to the Design Docs from #147

**Comment by heatherlarsen** [comment]
Is this one good to be closed with the updates from #187?

**Comment by amyrlam** [comment]
yes it's there https://flight-git-melsumner-design-docs-hashicorp.vercel.app/design#h2-contributing, closing!
