### ISSUE TITLE
update docs to read new catalog.json format

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/flight#176]
As part of the export work the format of catalog.json will be changing. We need to update the docs site to

- [x]  read this format instead (and if the format isn't working feed that back into the export work @didoo is doing)
- [x] Search also on the values in `description`

```
{
  "lastRunTimeISO": "2021-09-09T15:53:34.232Z",
  "lastRunFigma": {
    "id": "TLnoT5AYQfy3tZ0H68BgOr",
    "page": "Export",
    "frames": [
      "Core",
      "Services"
    ]
  },
  "assets": [
    {
      "id": "350:23",
      "fileName": "activity-24",
      "iconName": "activity",
      "description": "activity, pulse, health",
      "size": "24",
      "width": 24,
      "height": 24
    },
    {
      "id": "350:25",
      "fileName": "activity-16",
      "iconName": "activity",
      "description": "activity, pulse, health",
      "size": "16",
      "width": 16,
      "height": 16
    },
    {
      "id": "350:31",
      "fileName": "alert-circle-24",
      "iconName": "alert-circle",
      "description": "alert, circle, error, attention",
      "size": "24",
      "width": 24,
      "height": 24
    },
...
  ]
}
```

**Note: We can open a PR validating this without but wait to merge it until the export is finished**

**Comment by didoo** [comment]
@Dhaulagiri it may be that we need to include the new assets (otherwise the catalog will be out of sync with the SVGs in the repo)

**Comment by didoo** [comment]
now that #183 has been merged, this one is ready to be picked up (probably @MelSumner next week?)

**Comment by Dhaulagiri** [comment]
See #179
