### ISSUE TITLE
Ember addon <SVG> - fill vs style

### ISSUE THREAD

**Issue by didoo** [hashicorp/flight#200]
In the new Node pipeline I have moved the "currentColor" declaration from the <SVG> node directly in the <path> nodes (see #196). The reason for this is that now we don't "build" anymore the SVGs via script, we download directly from 
Figma, and Figma of course doesn't provide the `fill` in the <SVG> node. To have that, would have meant to do SVG manipulation, which I decided to avoid because:
- it's more common to have the `currentColor` applied directly on the paths (for example in future we could have multi-color icons, in which case makes even more sense)
- it allows us to have the standalone SVGs with the `currentColor` value directly in the paths (they will be consumed by React via `InlineSvg`)

I have realized that there's a problem with this: the Ember addon uses the `fill` attribute on the <svg> to apply the `color` prop. What I am suggesting here is to change the way we apply this color. 

Currently the prop value is applied as fill:
```
<svg [...] fill="{{this.color}}" />
```
but I suggest to apply it as inline style:
```
<svg [...] style="color: {{this.color}}" />
```

@MelSumner if it's OK for you, I can easily prepare a PR. Otherwise, if you have other suggestions, I'm all ears.

**Comment by meirish** [comment]
Using inline style is disallowed for HCP's Content-Security-Policy (and I think for Vault's as well?), so I don't think `style` will work for those apps.

**Comment by meirish** [comment]
Oops forgot to link https://github.com/jelhan/ember-style-modifier - we could use that in the ember addon to apply styles in a CSP-safe fashion, in the provided component, but I'm not sure if there are other considerations.

**Comment by MelSumner** [comment]
> Using inline style is disallowed for HCP's Content-Security-Policy (and I think for Vault's as well?), so I don't think `style` will work for those apps.

Ember will also throw an error if you use inline styles.

**Comment by MelSumner** [comment]
I can work around this change but if we could have an `isFullColor` property from the Figma API that would be nicer/easier.

**Comment by didoo** [comment]
@MelSumner can you expand on this? I don't follow/understand

**Comment by MelSumner** [comment]
@didoo: 
appending `-color` to the name of the icon is going to prevent users from setting a fill, so I was thinking I could conditionally support the `@color` property by doing this: 
- check to see if the name of the icon (`this.args.name`) includes '-color'
- if it does, don't include the `fill` attribute on the component
- maybe give an error message that the `@color` can't be set on a full-color icon?

But, I just tried removing the `fill` attribute entirely to see what would happen, and I don't see any color on the color icons at all. So I wonder if something else is going on here? 

(cc @Dhaulagiri )

**Comment by didoo** [comment]
> appending -color to the name of the icon is going to prevent users from setting a fill

don't understand, why? the `-color` part at this point is just part of an icon name/file, not anymore an attribute/prop

if there is no "simple" way to have the paths inside the SVG inherit the color via currentColor, then I prefer to fix it on the Node side (but this means treat differently the SVGs for Ember and the standalone SVGs, which is another "special case" to handle).

>  I just tried removing the fill attribute entirely to see what would happen, and I don't see any color on the color icons at all.
From what I've seen doing a test, is that if you completely remove the `fill` from the SVG node in `ember-flight-icons/addon/components/flight-icon.hbs` on "hover" the mono icons still get the (blue) color, because the color is inherited from the parent, via `currentColor` in the path. The problem is when you need to pass a color to the FigmaPath to "tint" the mono icon at runtime: in that case, my solution was to use an inline style, but this is not OK as mentioned above. So what are the alternatives? I don't think overcomplicating the API of the component is worth it, so at this point I'll change the Node script. If there's no workarounds... ¯\_(ツ)_/¯

**Comment by didoo** [comment]
This will be fixed in #215

**Comment by didoo** [comment]
For the sake of argument, how would you build a web color picker in Ember that satisfies the CSP? Probably is not possible, right?

**Comment by amyrlam** [comment]
Just noting to help with all the project management things, I think https://github.com/hashicorp/flight/pull/215 could have said `Resolves: <this issue url>` to close this issue, we can close it now?

Don't have enough context on color pickers in Ember yet to answer that question. But I would look at Ember Observer for any Ember addons https://emberobserver.com/?query=color%20picker. A lot of Ember addons are often a wrapper of some Vanilla JS implementation so may not be that applicable though.

**Comment by didoo** [comment]
> Just noting to help with all the project management things, I think #215 could have said `Resolves: <this issue url>` to close this issue, we can close it now?

Yes, closing it.
