### ISSUE TITLE
Internal: jquery test scenario not passing

### ISSUE THREAD

**Issue by MelSumner** [hashicorp/flight#207]
jquery is still a test scenario in ember-try. It's currently not passing. We should figure out how to make it happy or remove it from the test scenario list.

**Comment by Dhaulagiri** [comment]
Is there a specific point at which it stopped passing?

**Comment by Dhaulagiri** [comment]
It looks like something with the docs changes has introduced some [flakiness in our tests](https://github.com/hashicorp/flight/pull/208/checks?check_run_id=3603559453)

**Comment by amyrlam** [comment]
I also saw ember-release fail here: https://github.com/hashicorp/flight/pull/210

It should be solved by this https://github.com/hashicorp/flight/pull/209#discussion_r708645146, I may quickly try Percy today (and timebox) cause may be a better test anyways? Please LMK if I am missing something

**Comment by MelSumner** [comment]
I started noticing the flakiness after hooking up the toggle this morning. I might have inadvertently introduced a race condition, will need to track it down more.

**Comment by amyrlam** [comment]
This should be solved as I removed `assert.dom('[data-test-target="icon-grid"] [data-test-icon]').exists();` which wasn't in the DOM https://github.com/hashicorp/flight/pull/209#discussion_r708645146. Removed as a part of the Percy test replacement https://github.com/hashicorp/flight/pull/211. It was that test failing thruout the various scenarios.

Please reopen if you see again though!

**Comment by Dhaulagiri** [comment]
I don't think this is actually solved as we are simply masking the problem by not testing for it now. We haven't actually solved the underlying issue with there being some unpredictable delay in how quickly the sprite gets loaded. Perhaps that's will be a moot point though if we need to change how the sprite is loaded for https://github.com/hashicorp/flight/issues/198

**Comment by amyrlam** [comment]
ok, this relates to https://github.com/hashicorp/flight/pull/209#discussion_r709262671 cause the only test failing was cause of the DOM thing? let me reopen and track that work here

**Comment by amyrlam** [comment]
i'll wait for https://github.com/hashicorp/flight/issues/31 to land
