### ISSUE TITLE
Proposal: change folder structure/organization of the "app" for the Ember addon in Flight

### ISSUE THREAD

**Issue by didoo** [hashicorp/flight#217]
This is a proposal based on a general feeling that something is off in how we have organized and how we're using the `/tests/dummy/app` in the `ember-flight-icons` folder of the repository.

At the moment the "test/dummy" app is not dummy at all, and is not just for testing: it's the mini-website that we use to publish and document the Flight icons set. But now we use it also with Percy (#211). It's doing different things, with different goals.

My suggestion is to split responsibilities, and in doing so even improve our testing (expecially the visual regression testing).

- **mini-website** - the mini-website becomes a "standalone" app that consumes the icons as NPM package/dependency, and is located at the root of the project (`/mini-website` or just `/website`)
- **/tests/dummy/app** - for this one we create a no-frills app specifically built for testing; for example I would imagine to test not the whole icon page (when we add an icon, all the grid items shift position, and so the check is not specific enough) but have an "index" page with links to a sub-page where we can test a single icon (so spot potential changes coming from Figma that were unexpected/unintended). In doing so, we can also test different conditions:
    - icon with standard size(s)
    - icon with custom size
    - icon with color unspecified (so currentColor) + parent with custom color (to check inheritance)
    - icon with custom color specified via prop
    - icon with custom color specified via prop + parent with "color !important" declared (to check overrides)

in this way for example I probably could have spotted earlier some issues like #200.

Again, this is a proposal and we can discuss it and potentially postpone it for the post Flight 1.0 release, but please have a thought about it.

**Comment by MelSumner** [comment]
I agree with you that in the context of the whole design system it doesn't make sense to leave it there. 

- I see this as a temporary state, and only until we decide on a name for the design system. 
- Once we do, I see us creating hcds-website (or something like that) as a repo, and moving the content there. 
- We can re-direct the URL to get to the correct place

**Comment by amyrlam** [comment]
We've sorted the test portion here https://github.com/hashicorp/flight/issues/231  ... it seems very lightweight and no need to spin up a separate app just for that? Happy to iterate on testing as well.

As for the mini-website, eventually icons will need to be embedded in the whole design system. It isn't clear to me if we're moving forward with Storybook or other, but seems like could evaluate the icon website then?

**Comment by didoo** [comment]
OK, closing it for now.

@amyrlam re. the whole design system website, no decision has been taken yet. This will be a complex decision, with a lot of things to consider, and will require a proper analysis, discussion and evaluation. So, will be done much later (for the "scrappy" version we want to deliver next month or so, very likely we'll use Storybook, but only for the reasons that most of the existing product-specific styleguides are in Storybook too; but we'll talk about it in the planning session next week)
