### ISSUE TITLE
Add a Percy test for a single icon, multiple cases

### ISSUE THREAD

**Issue by amyrlam** [hashicorp/flight#231]
From conversation with @didoo, add a route with no navigation to it e.g. /percy. Just making the ticket to work in the open, isn't super high priority. 

Testing the overall page is good, but if we add an icon, the Percy diff won't be that impactful. 

Test the look of a single icon there, with multiple cases:
- normal
- with parent color, also consider !important (hopefully don't have to use !important though)
- changing color of icon
- maybe more?

**Comment by didoo** [comment]
@amyrlam copypasting from #217 

- icon with standard size(s)
- icon with custom size
- icon with color unspecified (so currentColor)
- icon with color unspecified (so currentColor) + parent with custom color (to check inheritance)
- icon with custom color specified via prop
- icon with custom color specified via prop + parent with "color !important" declared (to check overrides)
