### ISSUE TITLE
figma export should contain synonyms

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/flight#24]
Extracted from [here](https://github.com/hashicorp/flight/issues/5#issuecomment-893014116), when we export the icons from figma there is a series of description attributes we want to export to utilize in our search functionality.

`Description` will be added:

```
[
  {
    "Name":"activity-24",
    "Size":24,
    "Description":"activity, pulse, health"
  },
  ...
]
```

**Comment by didoo** [comment]
@dizzyup @Dhaulagiri likely this will be done in the context of #28

**Comment by Dhaulagiri** [comment]
Closed by https://github.com/hashicorp/flight/pull/164
