### ISSUE TITLE
Bump both packages

### ISSUE THREAD

**Issue by amyrlam** [hashicorp/flight#240]
- [x] @amyrlam can take another stab at the directions before Monday and tag us all in a PR for review. (https://github.com/hashicorp/flight/pull/242)
  - [x] Add ways to QA the release e.g. submit a PR to boundary for `@hashicorp/flight-icons` and bump in https://github.com/hashicorp/design-system-playground for` @hashicorp/ember-flight-icons`
- [ ] @MelSumner could run the steps on Monday "blind" just following the docs (to QA or dogfood our own instructions), as `1.0.0-rc.0` for `@hashicorp/ember-flight-icons` and `@hashicorp/flight-icons` 

cc @didoo 

_Originally posted by @amyrlam in https://github.com/hashicorp/flight/pull/229#discussion_r711279384_

**Comment by didoo** [comment]
OK for me

**Comment by didoo** [comment]
@amyrlam yesterday @MelSumner has bumped the version to _0.0.9-rc_ for `flight-icons` and _0.0.3-rc_ for `ember-flight-icons` so I would consider this task closed. I would prefer to do a second run of release with @Dhaulagiri today, to see his take on the documentation, before making changes to the markdown files (I'll open an issue to discuss the options we have).

**Comment by amyrlam** [comment]
👍 sgtm

FWIW i think the "terminal UI" will only work if it's `0.0.9-rc.0`

**Comment by amyrlam** [comment]
Product I used to work on uses `2.0.0-beta.0` so seems like `1.0.0-rc.0` would make sense https://docusaurus.io/docs/next

It's confusing that @didoo mentioned the SemVer page using https://semver.org/spec/v1.0.0-beta.html, but then also https://semver.org/spec/v2.0.0-rc.1.html

No preference just adding the context here in case someone goes back to look at this issue!

**Comment by didoo** [comment]
Version 1.0.0 has been released now, so we can close this one.
