### ISSUE TITLE
Design Docs: Match Figma

### ISSUE THREAD

**Issue by heatherlarsen** [hashicorp/flight#257]
#241 introduces updated design documentation, but one enhancement is to make it match the [Figma docs](https://www.figma.com/file/TLnoT5AYQfy3tZ0H68BgOr/Flight-Icons?node-id=636%3A137) as close as possible. 

**List of enhancements**
- [ ] Custom lists (using yes, warning, no icons)
- [ ] Changing our all `<em>` elements to custom tag/badge styles to easier readability
- [ ] Changing dimension list images into proper icons

## Screenshots ##
<img width="832" alt="Screen Shot 2021-09-21 at 11 36 34 AM" src="https://user-images.githubusercontent.com/8553306/134211072-e3e5ca4f-7704-40e5-9bf6-d07684f11a12.png">

**Comment by amyrlam** [comment]
@heatherlarsen closing issues related to the flight docs for now as a "won't do", but feel free to reopen in https://github.com/hashicorp/design-system/issues or file in asana if this is worked on later cc @Dhaulagiri
