### ISSUE TITLE
Look into Sourcegraph batch changes

### ISSUE THREAD

**Issue by amyrlam** [hashicorp/flight#260]
For https://www.npmjs.com/package/@hashicorp/flight-icons 0.0.6-beta to 0.0.9-beta, we made a breaking change with the namespacing and I simply forgot to update `learn`, forgetting that they were live with the package (sorry again!)

Also, we should start to get more strict on SemVer, even in beta releases, even though we will be at a 1.0.0 soon. 

I manually made this change in `boundary-ui` https://github.com/hashicorp/boundary-ui/pull/761. 

Look into Sourcegraph Batch Changes for potentially automating this process https://sourcegraph.com/batch-changes. I've just set up Sourcegraph and I _think_ I'm on the company account thru marketing. Let me look at it a bit on my own and then might sync with @kendallstrautman to improve this process!

**Comment by kendallstrautman** [comment]
@amyrlam I added you [to this repo](https://github.com/hashicorp/mktg-sourcegraph-campaigns) where we keep previous batch campaigns that we have run. Could be some useful examples! I used this tool a lot when doing wide sweeping branding updates across all the web properties, specifically with swapping color tokens etc.

**Comment by kendallstrautman** [comment]
Just added the whole design systems team so they can check it out too

**Comment by amyrlam** [comment]
@kendallstrautman thank you! I will check this out by the end of the week. It sounds really great

**Comment by amyrlam** [comment]
@kendallstrautman FWIW I don't think I'm on the account. I got an email from someone at Sourcegraph this morning asking if I should be added to the account. Please feel free to hold off on adding me / Design Systems to the account rn.

I floated this with the Design Systems team today and sounds like we will icebox this for now and potentially look into this later, as we don't have that many consumers rn / may not be desired. cc @didoo @Dhaulagiri @MelSumner

//

Sourcegraph person mentioned the Slack channel #sourcegraph-hashicorp (internal only), which I just joined!

**Comment by amyrlam** [comment]
I can close this for now since doesn't seem like something we will support at this time, but hope to revisit in the future!
