### ISSUE TITLE
How to re-organize the documentation about contribution, development and release of the Flight artefacts

### ISSUE THREAD

**Issue by didoo** [hashicorp/flight#265]
Yesterday @MelSumner gave some interesting feedback while following the instructions on how to release a new version of `flight-icons` and `ember-flight-icons`: to separate the contribution part and the release part of the documentation, following this example:
- https://github.com/emberjs/ember.js/blob/master/RELEASE.md
- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md

At the beginning it looked a perfect solution, but once I started to make the changes, I found myself stuck in a lot of doubts, mainly around the information architecture and organisation of our documentation in markdown in the repo. So I'll share with you team to see if you can come up with a solution.

# Context

At the moment we have a mono-repo containing three "artefacts"

- **the micro-website** 
    - the code is inside the `ember-flight-icons/tests/dummy` folder
    - is updated frequently and the PRs are directly merged in main once approved
    - there's no manual "release", it gets automatically redeployed every time
    - it doesn't have "consumers"
- **the `flight-icons`** 
    - the code is inside the `flight-icons` folder
    - is updated whenever an icon is updated (manually, there are manual scripts that need to be called to "build" the artefacts)
       - these scripts update also the `ember-flight-icons` content
    - it requires a manual "release" to [npm](https://www.npmjs.com/) in two steps, "bump" and "release" (each of them needs to be approved in a PR, plus this process is for both `flight-icons` and `ember-flight-icons`)
    - external codebases consume the npm package, so whenever there is an update they need to bump the version of the dependency
- **the `ember-flight-icons`** 
    - the code is inside the `ember-flight-icons` folder
    - is updated:
        - whenever an icon is updated (see above)
        - whenever there are changes to the `<FlightIcon>` component
    - it requires a manual "release" to [npm](https://www.npmjs.com/) in two steps, "bump" and "release" (and this can be done in the context of the icon update, so for both packages, or just for the addon)
    - external codebases consume the npm package, so whenever there is an update they need to bump the version of the dependency

Now, as you see there is **a lot** of implicit knowledge in all of this. We've tried to write down this knowledge in the markdown files in the repository, and this is the current structure:

```
flight/
├── README.md - general overview of the project with link to sibling CONTRIBUTING.md
├── CONTRIBUTING.md - essentially just links to /flight-icons/CONTRIBUTING.md and /ember-flight-icons/CONTRIBUTING.md
├── ember-flight-icons/
│   ├── README.md - general overview
│   └── CONTRIBUTING.md - explanation of how to setup and use the project + basic release instruction
├── flight-icons/
│   ├── README.md - general overview
│   └── CONTRIBUTING.md - detailed explanation of how to setup the project, how to update/build the icons packages, and how to bump and release the packages (included the ember addon)
│   ...
```
- [/CONTRIBUTING.md](https://github.com/hashicorp/flight/blob/main/CONTRIBUTING.md)
- [/ember-flight-icons/CONTRIBUTING.md](https://github.com/hashicorp/flight/blob/main/ember-flight-icons/CONTRIBUTING.md)
- [/flight-icons/CONTRIBUTING.md](https://github.com/hashicorp/flight/blob/main/flight-icons/CONTRIBUTING.md)

# Possible changes
Now, if we want to split the "contributing" from the "releasing" documentation (and this is also to be discussed: in which case you want to "contribute" but not release? we don't have a release cycle of months, every time me make a change to an icon or to the addon, we likely want to release immediately the change once approved/merged) we could have two options:

```
flight/
├── README.md
├── CONTRIBUTING.md
├── RELEASING.md ← This would be new and collect all the info about releasing 
├── ember-flight-icons/
│   ├── README.md
│   └── CONTRIBUTING.md
├── flight-icons/
│   ├── README.md
│   └── CONTRIBUTING.md
``` 

or 

```
flight/
├── README.md
├── CONTRIBUTING.md
├── ember-flight-icons/
│   ├── README.md
│   ├── CONTRIBUTING.md
│   └── RELEASING.md ← This would be new and collect all the info about releasing new icons
├── flight-icons/
│   ├── README.md
│   ├── CONTRIBUTING.md
│   └── RELEASING.md ← This would be new and collect all the info about releasing a change to <FlightIcon>
```

# Conclusion

Now, I have a small preference for the first option (single RELEASING.md file in the root), at least we can avoid the duplication of instructions (and potential confusion) between `flight-icons` and `ember-flight-icons`. Plus, we may want (why not, at this point) have a small entry also about how to release the mini-website (which is essentially explain that there is nothing to do, it's automatically deployed on merge, but is better to write it down anyway).

One consideration in this case is: what remains in CONTRIBUTING.md then? almost nothing :)

@MelSumner @Dhaulagiri @heatherlarsen @amyrlam and possibly @dizzyup, ideas? suggestions? strong opinions?

PS: before making a final decisions, I would like to do another test release with @Dhaulagiri this time, to see how he can follow the existing documentation, and see if he has other feedback too as a "user".

**Comment by MelSumner** [comment]
1. I agree with moving the release instructions to`RELEASE.md`.
2. I have no preference if there is just one set of release instructions for everything or multiple files with specific instructions, but we should choose a path and stick with that for the rest of our components. 
3. Can HashiCorp employees contribute to our code? If so we should have both a `CONTRIBUTING.md` file, telling them how to do this, and also add a `CODE_OF_CONDUCT.md` file.

Side note: are we compiling a list of things that we will need to add to each repo? At least for Ember Addons we can turn that into its own addon and install it as a devDep on each new repo.
