### ISSUE TITLE
Flight Icon Request: Services - EKS and EC2

### ISSUE THREAD

**Issue by dizzyup** [hashicorp/flight#318]
Needed to support a new selection interface in HCP Consul:

![screen_shot_2021-10-11_at_9 31 12_am](https://user-images.githubusercontent.com/717867/137109140-1cbabded-331b-4360-8d01-766b34f62f42.png)

Planning on adding these at the end of the week.

**Comment by dizzyup** [comment]
Added in Figma - pending review and release process cc/ @heatherlarsen

**Comment by Dhaulagiri** [comment]
@dizzyup  do we know who requested these icons?

**Comment by heatherlarsen** [comment]
@Dhaulagiri Emma Luo for HCP Consul

**Comment by heatherlarsen** [comment]
Thanks @Dhaulagiri! Emma has been notified via Slack :)
