### ISSUE TITLE
Flight Icon Request: HashiCorp products

### ISSUE THREAD

**Issue by sabrinako** [hashicorp/flight#330]
**Outline the use case for the new icon.**
Waypoint utilizes the logos of various HC products throughout, and we're in the middle of adopting the Flight icon library.

**If there's a similar existing icon, why isn't it a good fit? Please describe.**
There isn't any HashiCorp product logos 😢 

**Additional context**
Notable edge case is the Waypoint logo on the login screen which is larger than the 16 or 24 size dictated by Flight.

**Comment by heatherlarsen** [comment]
@sabrinako Thanks for the request. Could you please add a screenshot or link showing the Waypoint edge case you mentioned?

**Comment by sabrinako** [comment]
<img width="721" alt="Screen Shot 2021-11-10 at 3 12 08 PM" src="https://user-images.githubusercontent.com/60155296/141186416-e56b4e2d-55f6-4bc0-abcd-976c841e2af1.png">
The Waypoint logo in the middle of the screen is the edge case I mentioned!

**Comment by amyrlam** [comment]
Cross-posting this PR from @didoo, may complete the issue? https://github.com/hashicorp/flight/pull/341

**Comment by didoo** [comment]
@amyrlam yes, you're right! I completely forgot about this particular open issue! I am closing it now.

@sabrinako FYI the product icons are now available both in Figma (as Flight Icons, usual standard library) as well as in code (version `2.0.0` of the icons, in which case careful is a breaking change)
