### ISSUE TITLE
Flight Icon Request: Pack

### ISSUE THREAD

**Issue by sabrinako** [hashicorp/flight#331]
**Outline the use case for the new icon.**
Waypoint has a Pack plugin, which any metadata with this plugin has no logo associated with it

**If there's a similar existing icon, why isn't it a good fit? Please describe.**
Currently using the `package` icon in the meantime to fill the empty space. All other operations show a logo (GCP, AWS, Docker, etc) so it'd be nice to have the Pack logo as well

**Comment by heatherlarsen** [comment]
@sabrinako Can you please attach a screenshot or share a link to the icon the team was using before? And ones with the icon in context? Thanks!

**Comment by sabrinako** [comment]
<img width="555" alt="Screen Shot 2021-11-10 at 3 15 30 PM" src="https://user-images.githubusercontent.com/60155296/141186827-097f4086-e395-4e94-a678-fcfeee76d5d2.png">
I actually just realized that the SVG is being pulled from within the Waypoint repo. I might be able to work around this one, so I would recommend prioritizing getting the HashiCorp logo icons

**Comment by didoo** [comment]
If this icon is used in the product(s), it would be better to have it in the "Flight - Services" group. What do you think @dizzyup?

**Comment by heatherlarsen** [comment]
@didoo I think the fact that it's a plugin logo (?) and not a generic icon is what makes it a part of the "Services" group, not that it's used in the product(s). But yes, I agree this should go in "Services". I'll track this down in the Waypoint repo and pull it into Flight this week.

**Comment by heatherlarsen** [comment]
@sabrinako This icon has been added to Flight via #341
