### ISSUE TITLE
Icons don't load when consumed via storybook

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/flight#335]
@venusang and I paired on diagnosing a problem she was having using `ember-flight-icons` in storybook

### What I expected
I can compose stories in ember-cli-storybook that use icons via the `<ember-flight-icons>` component

### What happened
The icons don't appear. Top is storybook and bottom is in the app.

<img width="659" alt="CleanShot 2021-11-12 at 11 25 52@2x" src="https://user-images.githubusercontent.com/1672302/141848528-79cfc33f-360d-4f02-88f4-88392bd435ff.png">

### What we think the problem is

ember-flight-icons [relies on logic in the `contentFor` hook](https://github.com/hashicorp/flight/blob/1b0979ab47768ce08d501b62a2d97a014eb89d1d/ember-flight-icons/index.js?_pjax=%23repo-content-pjax-container#L14-L16) to insert the sprite into the DOM. It seems likely this logic is not working as expected in storybook.

**Comment by meirish** [comment]
I think adding a `.storybook/preview-body.html` file that does the same thing as the `contentFor` tag would fix this: https://storybook.js.org/docs/react/configure/story-rendering#adding-to-body

**Comment by Dhaulagiri** [comment]
@venusang @meirish I believe I recall that y'all ended up fixing this yes?
