### ISSUE TITLE
Flight Icon Request: [magic wand]

### ISSUE THREAD

**Issue by Ashtronaut09** [hashicorp/flight#339]
**Outline the use case for the new icon.**
Given the invention of 'insights' and automated magic that the user could consent to, we might want a 'magic' icon.

**If there's a similar existing icon, why isn't it a good fit? Please describe.**
no magic in our system lol

**Describe alternatives you've considered.**
A lightbulb, we also don't have that.

**Screenshots**
![image](https://user-images.githubusercontent.com/13004940/145031480-d5bc26ad-ffd1-44e7-ab56-043ab4d45925.png)

**Comment by cveigt** [comment]
Update: We will be adding this icon in the next release, along with the [Bulb](https://github.com/hashicorp/flight/issues/340).

<img width="131" alt="Screen Shot 2022-01-28 at 5 13 00 PM" src="https://user-images.githubusercontent.com/2142312/151641106-283dd5d5-3daf-45e2-93ea-f4d3166e0aec.png">

@Ashtronaut09, let me know if you have any comments or feedback before publishing on Figma.
