### ISSUE TITLE
Flight Icon Request: [lightbulb]

### ISSUE THREAD

**Issue by Ashtronaut09** [hashicorp/flight#340]
**Outline the use case for the new icon.**
Insights are suggestions for users to take action on their work, it is smart.

**If there's a similar existing icon, why isn't it a good fit? Please describe.**
Cant think of anything that is "smart"

**Describe alternatives you've considered.**
A magic wand.

**Screenshots**
![image](https://user-images.githubusercontent.com/13004940/145031652-203980e3-c445-4cda-85d6-f9f2d034f2b3.png)
![image](https://user-images.githubusercontent.com/13004940/145031717-6e7ae45d-1570-481b-b924-67813430188d.png)

**Comment by cveigt** [comment]
Update: We will be adding this icon in the next release.

<img width="131" alt="Screen Shot 2022-01-28 at 5 06 47 PM" src="https://user-images.githubusercontent.com/2142312/151640931-dc8dfb47-c3f8-4350-9f82-9d2d151e59da.png">

We'll also add the [wand](https://github.com/hashicorp/flight/issues/339) icon.
