### ISSUE TITLE
GitHub action doesn't trigger CI

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/flight#346]
https://github.com/hashicorp/flight/pull/322 created a github action for the build/sync process, but in practice the PR that is opened as a result of this is not correctly triggering the ci action to also run. This prevents the PR from being reviewed and merged.

We should either
* Ideally figure out why this is not working as expected and correct it
* or, less ideally, remove the action and associated documentation for it

**Comment by Dhaulagiri** [comment]
[This is the reason](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs). The step that creates the PR can't trigger subsequent workflows like our CI run.

**Comment by Dhaulagiri** [comment]
@didoo @MelSumner @amyrlam this is low priority, but if we want to be able to have this workflow work as expected we'll have to setup a personal access token in the action as outlined [here](https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-536204092) which I can do but...Main drawback being the PR would be opened in that person's name and that person could not approve/request changes on the PR. And if that person disappeared from the company the token would also break.

👍  or 👎  any thoughts?

**Comment by MelSumner** [comment]
@Dhaulagiri this is def not my domain of expertise, I usually rely on someone else on the team to handle these things. I will defer to the rest of the team in this case.

**Comment by didoo** [comment]
my feedback is this: **in theory** using GH actions for automatically open PRs for the Flight icons is the perfect solution; **in practice** is solving a problem that probably we don't have, with all the drawbacks that we have seen. for me, we can even remove this automated task.

(one more useful would be to bump&release via single click/action; if only we could specify a parameter in the action which is the bumped version)

**Comment by amyrlam** [comment]
If keep the action, start with you, but ask Helpdesk if they can create a "shared" user so token not tied to an individual? Wouldn't be surprised if there already was one or more at the company TBH
