### ISSUE TITLE
Flight Icon Request: ecs

### ISSUE THREAD

**Issue by natmegs** [hashicorp/flight#348]
**Outline the use case for the new icon.**
Flight currently has `eks` and `ec2` icons - would it be possible to add `ecs` as well?
The current use case is for HCP Consul, where we have a Terraform quickstart feature which provides users the option to deploy Consul with clients running on either `eks` or `ec2` and we are currently working on adding support for `ecs` in addition.

**If there's a similar existing icon, why isn't it a good fit? Please describe.**
Specific product icon

**Describe alternatives you've considered.**
Using bespoke svg with structure Icon component

**Screenshots**
https://aws.amazon.com/ecs/
![image (3)](https://user-images.githubusercontent.com/19582796/146280899-dfa574ec-53a2-44be-876d-f878daa64791.png)

**Figma**
TBD! It will be added [here](https://www.figma.com/file/jbFgme6N06DeArtn0grTkk/HCP-Consul---Activation-II---TF-Provider?node-id=1052%3A54238)

**Additional context**

**Comment by natmegs** [comment]
@heatherlarsen would it be possible to add an outline version as well? 
![image (4)](https://user-images.githubusercontent.com/19582796/146282052-37badfa0-77ec-439c-b05f-3d4aaec7a209.png)

**Comment by heatherlarsen** [comment]
@natmegs We currently only support a mono version and a color version for services, but let me take this back to the team and see if it's something we can support. Will keep you in the loop.

**Comment by heatherlarsen** [comment]
@natmegs after speaking with the team prior to break, what we're looking for with Service icons is the official logo, so if the official logo is outlined then we would use that but if it's solid, then we'd use the solid version. I'm having a bit of trouble tracking the official version for this one, but will keep looking.

**Comment by heatherlarsen** [comment]
@natmegs I spoke with our AWS Marketing Partner reps today and they informed me that Amazon will be updating their usage guidelines and hopefully providing the official versions of each of the service icons in February, so at this point we're just waiting on them to release that. Is there a deadline for this on your end?

**Comment by cveigt** [comment]
Update: After all the work that @heatherlarsen has done, partnering with marketing and tracking down design guidelines, we have a logo aligned with AWS usage guidelines.

We'll be adding these two icons to Flight.

<img width="257" alt="Screen Shot 2022-02-22 at 4 31 42 PM" src="https://user-images.githubusercontent.com/2142312/155243033-17434f61-50ea-46b2-9354-c2ccef027884.png">

**Comment by cveigt** [comment]
CC @didoo

**Comment by natmegs** [comment]
@cveigt @heatherlarsen we had been chatting offline but I forgot to post here as well - thank you so much for the help with this!! Really appreciate it
