### ISSUE TITLE
Change name on icon viewer to not include the size

### ISSUE THREAD

**Issue by amyrlam** [hashicorp/flight#350]
From a Slack thread with cloud-ui, they thought that the name would be `@name='terraform-color-16'`. It would be a nice improvement to the DX and UX to not show this!

![image](https://user-images.githubusercontent.com/1372946/146475530-982d2186-1e6b-4089-8c15-43c8dc1c7412.png)

**Comment by amyrlam** [comment]
cc @jesdavpet @LINDGRENBA (didn't include the thread link because is internal)

**Comment by didoo** [comment]
@amyrlam for the React developers, that inline the SVGs directly, this is the name that they need. so we need to show both:
- SVG name: `activity-16`
- Icon name: `activity`
