### ISSUE TITLE
Flight Icon Request: [vault-color] (update)

### ISSUE THREAD

**Issue by didoo** [hashicorp/flight#372]
**Outline the use case for the icon update.**
@ashleemboyer has highlighted a use case for the Vault (color) icon that is not supported by the current icon in Flight:

<img width="387" alt="screenshot_695" src="https://user-images.githubusercontent.com/686239/148945661-153f01cc-7326-4ff5-a7be-924247b35638.png">

Currently in Flight the `vault-color` icon is an outlier:
<img width="1084" alt="screenshot_696" src="https://user-images.githubusercontent.com/686239/148945807-1cff593d-8b76-4775-8e48-bec36d1d4c86.png">
but from the _brand_ color perspective we should use the yellow color for that icon
<img width="552" alt="screenshot_697" src="https://user-images.githubusercontent.com/686239/148945929-7e4bf856-78cf-4180-bc66-ed728550eb9c.png">

Now, the reason for having the black colored version was that we were waiting for a redesign of the Vault logo by the marketing team. Now this redesign has happened (the difference is in the number of squares inside the logo) and it's available in the [02 - Global Assets v2.0](https://www.figma.com/file/aeLMZnYDsUAeEOUadjtjgP/02---Global-Assets-v2.0?node-id=2912%3A16277) file.

After quick chat with @dizzyup we have agreed that it's safe to update the `vault-color` icon in flight https://flight-hashicorp.vercel.app/?query=vault-color to use the brand color (yellow) and not the "alt" one. This will impact the IconTile component, but @dizzyup says it's OK.

<img width="1328" alt="screenshot_700" src="https://user-images.githubusercontent.com/686239/148946779-c4bf1627-79a3-4b97-b0a1-c5b11c1f03db.png">

Please @heatherlarsen @cveigt can you update the icon in the Figma files, so we can release a new version? Thanks

**Comment by didoo** [comment]
@heatherlarsen @cveigt the brand color for Vault has been updated by the marketing team (see https://github.com/hashicorp/design-system-tokens/pull/59) please update it also in the UI Kit libraries before updating the icon, so we're sure it uses the right color.

**Comment by cveigt** [comment]
@didoo, I've updated the color in the UI kit and the logos/icons in Flight as well. Once the changes are approved, and the library is published, I'll let you know.

**Comment by didoo** [comment]
For future reference, here's the marketing presentation about the change in the logo color/design: [Vault Logo Color and Visual Refinements](https://docs.google.com/presentation/d/1EsUsMkTrSd53qKntDmsHEbjdirc1OhU38ajXfThx80I/edit#slide=id.g104d2e9b90a_1_186)

**Comment by didoo** [comment]
@ashleemboyer version `2.0.2` of the flight icons has been released, it contains the updated version of the Vault icon.
Let me know if you have any issue.
