### ISSUE TITLE
Flight Icon Request: service

### ISSUE THREAD

**Issue by jnwright** [hashicorp/flight#397]
**Outline the use case for the new icon.**
an icon to designate services (could be useful for both Consul and Nomad)

**Describe alternatives you've considered.**
we currently have the "cluster" icon as a stand-in, but feel like that's too general

**Screenshots**
![image](https://user-images.githubusercontent.com/16551527/152235457-6b01ff14-2f68-432d-aefd-2c7b9ec9ae58.png)

**Figma**
[Consul Overview UI](https://www.figma.com/file/qlD6mJxNCtDvy4LarWWqHL/Overview?node-id=1535%3A9066)

**Additional context**

**Comment by cveigt** [comment]
We will be adding this icon in the next release.

<img width="123" alt="Screen Shot 2022-02-22 at 1 00 12 PM" src="https://user-images.githubusercontent.com/2142312/155243831-d836fe9a-90c1-4eb3-8950-c4b2ac345abc.png">

It was already shared with @jnwright.

**Comment by cveigt** [comment]
CC @didoo
