### ISSUE TITLE
Locally linking ember-flight-icons in website doesn't work

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/flight#407]
### Steps to Reproduce
```bash
cd ember-flight-icons
yarn link
cd ../website
yarn link @hashicorp/ember-flight-icons
yarn start
```

### What happens
<img width="918" alt="Screen Shot 2022-02-11 at 08 26 37" src="https://user-images.githubusercontent.com/1672302/153609202-0784f2e9-ee8d-4bb5-b202-ff7f1c7241c1.png">

### What I expect
The website load as normal

**Comment by Dhaulagiri** [comment]
Note: this issue came up trying to experiment with these packages in a monorepo where linking is required for things to work. Hence a higher priority to figure out.

**Comment by didoo** [comment]
Yes, I saw the same error myself, while doing some tests, but I couldn't figure out what was the cause. Great to see it fixed :)
