### ISSUE TITLE
Consider fixing alphabetization of icons

### ISSUE THREAD

**Issue by amyrlam** [hashicorp/flight#417]
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/1372946/156098892-3e70dda2-c1b2-4f74-b0f8-0556911117f2.png">

`loading` and `running` appear first.

Suggestion: Have the name on the Flight website be `animation-loading` and `animation-running`.

Edit: Seems like they're ordered by type, then alphabetical (e.g. `slack` is with other corporate icons). Not sure if intended or not.

**Comment by MelSumner** [comment]
Is this a bug? I am okay with having the animated ones first, and then the rest sorted alphabetically. Is there some sort of drawback to leaving it this way?

**Comment by amyrlam** [comment]
@MelSumner It's not just the animated ones that are out of order. Company ones are also out of order, sorted by type (e.g. `waypoint` before `hashicorp` before `alert-circle`:

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/1372946/156265108-0fe438c1-c54e-49e3-b6c7-22a3888c118d.png">

For ~700 icons (and counting), not having a clear alphabetical order is arguably a bad user experience. 
- If we were to run user research on our own Flight docs, the average user would probably find it confusing.
- If we wanted to get data-driven, we could track how many people are searching vs. scrolling

Clear alphabetical order provides more value to our users, vs random order that is not clear or specified on the page. Even specifying how they are ordered when you scroll, or labeling the "sections", could be an improvement.

I personally could not find the icons for the Feb newsletter yesterday. I defaulted to scrolling. This is not high priority, but there is room for improvement in my book. If the team decides to close the issue, is also a-ok.

**Comment by Dhaulagiri** [comment]
I think this makes sense and would be relatively easy to implement. Right now we're just spitting back out the order of the icons from the `catalog.json` file which is "sorted" based on where the different icons live on the figma side of things.

**Comment by amyrlam** [comment]
Can close as a won't do for now vs move to the new repo
