### ISSUE TITLE
Warn consumers if they don't specify an icon

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/flight#43]
Given I am a consumer of the ember addon
And I do not specify an icon
I get a friendly error (or warning) notifying me that I need to specify an attribute

**Comment by MelSumner** [comment]
This is what they see now: 
![image](https://user-images.githubusercontent.com/4587451/130490629-5a0dee52-08ab-4457-81dc-575c1d6ead4b.png)

The message is set here in the component class, can be changed if we need something else instead: https://github.com/hashicorp/flight/blob/235dde2b8115ae0d7aa421d7c9da867ed0e7e761/ember-flight-icons/addon/components/flight-icon.js#L39 

By using `assert`, we have confidence that this will just be seen in dev environments only.
