### ISSUE TITLE
Determine how sprite will be published/consumed

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/flight#48]
Given I have created a version of the sprite using our build script
How will consumers (like our ember addon) consume the sprite file?

**Comment by didoo** [comment]
After discussion with @amyrlam we agreed that we can close this ticket. The sprite is never consumed as is, as deliverable/artefact, only inside the ember package (and also this is a temporary workaround until we figure out how to embed directly the folder; see #118)
