### ISSUE TITLE
Have this project added to our vercel deploys

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/flight#53]
Once we have an initial version to standup we'll need to add this repo to our vercel account and then get it configured to deploy the dummy app in ember-flight-icons (ideally for every PR as well)

**Comment by amyrlam** [comment]
i'm stuck in this loop, will xpost on slack ![vercel](https://user-images.githubusercontent.com/1372946/130537409-927512f5-a268-43a8-9fe9-ab4af4c0b2a5.gif)

**Comment by amyrlam** [comment]
update: pinged helpdesk
