### ISSUE TITLE
Add tests validating `color` behavior

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/flight#54]
Once https://github.com/hashicorp/flight/pull/34 lands we should add some integration tests that confirm the behavior of the `color` property work as expected.

**Comment by MelSumner** [comment]
To prevent duplicate work: 

Currently, these things have been verified: 
- `@color` (`fill`) is set to `currentColor` by default (see [the class](https://github.com/hashicorp/flight/blob/235dde2b8115ae0d7aa421d7c9da867ed0e7e761/ember-flight-icons/addon/components/flight-icon.js#L18) and [the template](https://github.com/hashicorp/flight/blob/235dde2b8115ae0d7aa421d7c9da867ed0e7e761/ember-flight-icons/addon/components/flight-icon.hbs#L6))
- `@color` accepts a named color, a [css variable](https://github.com/hashicorp/flight/blob/235dde2b8115ae0d7aa421d7c9da867ed0e7e761/ember-flight-icons/tests/integration/components/flight-icon-test.js#L54), or a color value (e.g. rgb(0,0,0))
- If `<FlightIcon @name="zap" @color="red" class="ds-fill-blue" />` is passed, where `.ds-fill-blue` defines the `fill` property set to the color blue, the CSS class will override the `@color` value: 
![image](https://user-images.githubusercontent.com/4587451/130491843-e8baa335-e9da-4b22-9095-d4409cb3df3c.png)
- If the icon is nested in a text node that has a CSS class defining color, the icon is still `currentColor`: 
`<span class="ds-text-red">Text is red <FlightIcon @name="zap" />.</span>`
![image](https://user-images.githubusercontent.com/4587451/130492195-8e1a8f94-fd3e-42ed-b5f4-b73012b5ce58.png)
