### ISSUE TITLE
Question: Default icon size decision

### ISSUE THREAD

**Issue by amyrlam** [hashicorp/flight#62]
i incorrectly assumed the default icon size was 16 in https://github.com/hashicorp/flight/pull/34. i thought that that was more common in ember repos, but i can do some investigation

it sounds like marketing / react mostly uses icons as 24 per https://github.com/hashicorp/flight/issues/60

by size, i mean the `viewBox` and the `height` and `width`, sans px or other measurement rn

**Comment by MelSumner** [comment]
I confirmed default icon size with @dizzyup before implementing in a component. 👍

**Comment by amyrlam** [comment]
cool thanks for the info, just curious why, is it more common? could add a one liner to the docs so is clear if others ask too

**Comment by dizzyup** [comment]
More common in product certainly - that was the lense I made that call through I think. I could totally see that not being the case on the marketing side though. 

I think maybe the answer here is that the React plugin, or whatever mechanism marketing come up with on their side, default to `24` and our Ember add-on maintains `16`.

**Comment by MelSumner** [comment]
@amyrlam yes correct. 👍  I even thought about finding out which icon was used the most so if they used `<FlightIcon/>` by itself they'd get at least something.

**Comment by amyrlam** [comment]
thanks for the context, made this tweak, lmk what you think: https://github.com/hashicorp/flight/pull/67
