### ISSUE TITLE
Missing icons from export?

### ISSUE THREAD

**Issue by amyrlam** [hashicorp/flight#68]
Was pairing with someone who made a new icon (this PR: https://github.com/hashicorp/cloud-ui/pull/1279), I noticed `check-hexagon-fill` from Figma didn't make it here. Should investigate if the script is working?

Maybe could a test for the # of exports matching the quantity # in Figma or something

**Comment by amyrlam** [comment]
i think it is there (confused) https://github.com/hashicorp/flight/blob/main/export-go/dist/check-hexagon-fill-16.svg

**Comment by Dhaulagiri** [comment]
> Maybe could a test for the # of exports matching the quantity # in Figma or something

This seems like a useful thing we should do as part of the export re-write. # of icons in = # of svgs generated

**Comment by dizzyup** [comment]
@amyrlam Is it possible the icons hadn't been added with the version they were playing with? The hex icons were among the most recent to get added.

Really like the idea of having a count to sanity check.

**Comment by Dhaulagiri** [comment]
Opened https://github.com/hashicorp/flight/issues/77 to track implementation of a sanity check

**Comment by amyrlam** [comment]
yeah... i think it was just missing in the moment, maybe because we weren't using the versioned npm package. since brian made https://github.com/hashicorp/flight/issues/77, seems like this can be closed. if you ever disagree on "done" though, def feel free to reopen
