### ISSUE TITLE
Fix export from Figma

### ISSUE THREAD

**Issue by amyrlam** [hashicorp/flight#75]
Some icons such as https://github.com/hashicorp/flight/blob/main/export-go/dist/chevron-up-16.svg are the wrong icon (is down, not up) and oddly cropped.

- Could fix in Go
- We may migrate the export from Go to Node, so now could be a good time to do that? Just adding for discussion
- Write tests / somewhat relates to https://github.com/hashicorp/flight/issues/68

Reported by: @randallmorey cc @hashicorp/design-systems

**Comment by MelSumner** [comment]
I noted that quite a few of the chevron icons are cut off/not displaying correctly.

**Comment by dizzyup** [comment]
Fixed in #76
