### ISSUE TITLE
Match number of icons from Figma with number of icons exported

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/flight#77]
Given I have N icons in the Figma file
The exporter should have a validation in place to confirm it generates N svgs

**Comment by didoo** [comment]
probably can be tackled in #28

**Comment by amyrlam** [comment]
Can also be cross-checked with https://github.com/hashicorp/flight/pull/211

**Comment by didoo** [comment]
@amyrlam what you mean? there is already a check in place here: https://github.com/hashicorp/flight/blob/73ec29b468e07ffb828a635a8e36633cd38f3cc5/flight-icons/scripts/sync.ts#L58, how Percy would check?

**Comment by amyrlam** [comment]
sounds good, let's mark it done! just discussed IRL
