### ISSUE TITLE
Default icon size should be 16

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/flight#78]
There's been some miscommunication around this, but the default icons size should be 16 and not 24. We'll need to update the component and the documentation to reflect this.

**Comment by amyrlam** [comment]
👍 sgtm I would have assumed that was the standard on the product Ember side given icons are often inline with text.

(slight tangent, but to share) FWIW some repos like `consul` are using a `viewBox` of 24 as default, but we should look at this more. `consul` consumes `iris`, they are stripping out the `height` and `width` and just using the `viewBox` https://github.com/johncowen/iris/blob/flight/bin/iris#L66-L85. Their version of "tree shaking" is to implement the svg's in CSS, not Ember-specific.
