### ISSUE TITLE
How to handle the dupe svgs from export-go to flight-icons

### ISSUE THREAD

**Issue by amyrlam** [hashicorp/flight#84]
The svg's from the Go export are duplicated in the Ember icon. Right now they are out of sync from the latest Figma export, I manually copied them in https://github.com/hashicorp/flight/pull/69.

Some ideas:
- Have Ember addon consume https://www.npmjs.com/package/@hashicorp/flight-icons. Right now I've been publishing the flight-icons addon on a not for merge PR (https://github.com/hashicorp/flight/pull/69). So we should get that sorted on main if good to go.
- ~Document manually copying the svgs from the Go export to ember-flight-icons/public/icons directory~ update: done

**Comment by Dhaulagiri** [comment]
As described option 1 seems most reasonable. The missing bit we need to solidify though is where does that actual sprite generation take place. An alternative to consider would be to have a build step available in the export node library that takes all the svgs and builds a sprite and then copies that file into the ember addon's public folder for use there.

**Comment by Dhaulagiri** [comment]
See also https://github.com/hashicorp/flight/issues/48

**Comment by MelSumner** [comment]
I was reading through the source code of `ember-mdi`, and it seems like that addon imports the mdi icons for use; this also allows for the configuration of only including the ones that you need. 

This could be an approach we consider.

**Comment by amyrlam** [comment]
from standup: change the export-go folder to put the icons in flight-icons/, if we make that change in https://github.com/hashicorp/flight/pull/118

**Comment by amyrlam** [comment]
(not urgent) right now i'm having trouble running the go script, so i can't test moving the folder:

```
flight (main) 🌘 ~ pwd
/Users/amyrlam/src/hashicorp/flight/export-go
flight (main) 🌘 ~ go run .
2021/09/01 15:49:40 Taking flight (development)
2021/09/01 15:49:40 Querying Figma file
2021/09/01 15:49:40 Error getting icons from Figma document
exit status 1
```

depends on https://github.com/hashicorp/flight/pull/138 so can revisit next week or beyond!

**Comment by didoo** [comment]
After discussion with @amyrlam decided to close it, will be tackled in #28 and followup epic.
