### ISSUE TITLE
Namespace icons

### ISSUE THREAD

**Issue by randallmorey** [hashicorp/flight#90]
Currently, icons live under `export-go/dist/`.  While it's possible to namespace icons in this location, it would be ideal if they were already packaged in a folder named `flight` (e.g. `../dist/flight/`).

Boundary would like to consume and use namespaced icons.

**Comment by amyrlam** [comment]
following up from slack, right now the npm tarball https://github.com/hashicorp/flight/pull/99/commits/d0c4a42a5f39efec7f1074cc1e8cb1a13de6b544 has all of the .svg's in a top level folder

we should have the npm of @hashicorp/flight-icons be committed to the repo for clarity

**Comment by amyrlam** [comment]
AL: Make a follow-on PR to https://github.com/hashicorp/boundary-ui/pull/720/files that uses 0.0.4-beta when published

**Comment by amyrlam** [comment]
closing as done. didn't realize that "done" does not close the issue
