### ISSUE TITLE
Consider adding Percy

### ISSUE THREAD

**Issue by amyrlam** [hashicorp/flight#93]
Would allow us to have some sort of test for visual changes re: https://github.com/hashicorp/flight/issues/87

**Comment by didoo** [comment]
+1 on this, we can even test both the full page of https://flight-staging.vercel.app/ and the single icons for better results (depends on how Percy scripting works; I used a custom solution built on top of Puppeteer for this and worked a charm)

**Comment by amyrlam** [comment]
Yeah as a first pass how it would work from my past experience is:

- set up testing
- visit url
- percy snapshot the page of all the icons

**Comment by amyrlam** [comment]
Wanted to add that we could potentially also set this up in `cloud-ui`, which may help us as they decouple structure / their own in-repo design system to migrate to flight icons / new design system. re: https://docs.google.com/document/d/1zd9vvh66uYVCbs90Ncknsp9yyIaQpt35-w_RyfvHWHo/edit?disco=AAAAOsVRXd4

**Comment by Dhaulagiri** [comment]
This would make more sense for us to consider once we solidify our approach to documentation as any setup work we did now would need to be redone for that.
